---
# Task file for cleaning up individual IAM users
# This file is included by mcp_aws_cleanup.yml

- name: "Delete user {{ user_name }} with force cleanup"
  ansible.mcp.mcp_run_tools:
    tool_name: delete_user
    tool_args:
      user_name: "{{ user_name }}"
      force: true  # This will remove all associated resources (policies, access keys, etc.)
  register: user_deletion
  ignore_errors: true
  
- name: "Display deletion result for {{ user_name }}"
  ansible.builtin.debug:
    msg: "{{ 'Successfully deleted' if user_deletion is succeeded else 'Failed to delete' }} user: {{ user_name }}"
