name: integration

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*

permissions: {}

jobs:
  integration:
    environment: protected # requires manual approval within GitHub Actions to proceed
    env:
      source: "./source"
      python_version: "3.13"
      ansible_version: "devel"
    runs-on: ubuntu-latest
    name: "ansible-test-integration"
    permissions:
      contents: read
    steps:
      - name: Checkout collection
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ${{ env.source }}
          ref: ${{ github.event.pull_request.head.sha }}
          allow-unsafe-pr-checkout: true
          persist-credentials: false   

      - name: Build and install collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@4678c74a7d712d55e663c88f66eec6d9c3642550 # main as of Aug 21, 2026
        with:
          install_python_dependencies: false
          source_path: ${{ env.source }}

      - uses: ansible/ansible-test-auth@008750a5bf07124c3ab86d30d73d7319d7518f36 # v1.0.0

      - name: Create integration config file
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
            GH_PAT_SECRET: ${{ secrets.ANSIBLE_MCP_GITHUB_PAT }}
            INTEGRATION_CONFIG_PATH: "${{ steps.install-collection.outputs.collection_path }}/tests/integration/integration_config.yml"
        with:
            script: |
                const fs = require('fs');
                const path = require('path');

                // 1. Retrieve data from environment variables
                const secret = process.env.GH_PAT_SECRET;
                const fileName = process.env.INTEGRATION_CONFIG_PATH;

                try {
                    // 2. Write the file
                    fs.writeFileSync(fileName, `github_mcp_pat: ${secret}`, 'utf8');
                    console.log(`Successfully created ${fileName}`);
                } catch (err) {
                    core.setFailed(`Failed to write file: ${err.message}`);
                }

      - name: Install collection ansible.utils
        run: ansible-galaxy collection install ansible.utils -p /home/runner/.ansible/collections/ --force
        shell: bash

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@4678c74a7d712d55e663c88f66eec6d9c3642550 # main as of Aug 21, 2026
        with:
          collection_path: ${{ steps.install-collection.outputs.collection_path }}
          python_version: ${{ env.python_version }}
          ansible_version: ${{ env.ansible_version }}
          ansible_test_requirement_files: "tests/integration/requirements.txt"